name: Deploy Go App to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AWS_REGION: ap-southeast-1
  ECR_REPOSITORY: go-web-app
  EC2_HOST: ${{ secrets.EC2_HOST }}
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build Go application
      run: |
        go build -o myapp main.go

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/go-web-key
        chmod 600 ~/.ssh/go-web-key

    - name: Deploy application
      run: |
        # Create systemd service file
        cat > go-web.service << 'EOL'
        [Unit]
        Description=Go Web Application
        After=network.target

        [Service]
        Type=simple
        User=ec2-user
        WorkingDirectory=/opt/go-web
        ExecStart=/opt/go-web/myapp
        Restart=always
        RestartSec=5

        [Install]
        WantedBy=multi-user.target
        EOL

        # Copy binary and service file to EC2
        scp -i ~/.ssh/go-web-key -o StrictHostKeyChecking=no myapp go-web.service ec2-user@${{ secrets.EC2_HOST }}:/tmp/
        
        # SSH into EC2 and setup service
        ssh -i ~/.ssh/go-web-key -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          # Create application directory
          sudo mkdir -p /opt/go-web
          
          # Copy files to correct locations
          sudo cp /tmp/myapp /opt/go-web/
          sudo cp /tmp/go-web.service /etc/systemd/system/
          
          # Set correct permissions
          sudo chown ec2-user:ec2-user /opt/go-web/myapp
          sudo chmod +x /opt/go-web/myapp
          
          # Reload systemd and enable service
          sudo systemctl daemon-reload
          sudo systemctl enable go-web
          
          # Start the service
          sudo systemctl start go-web
          
          # Check service status
          sudo systemctl status go-web
          
          # Clean up
          rm /tmp/myapp /tmp/go-web.service
        EOF